name: Build and Deploy Java App to Tomcat on EC2

on:
  push:
    branches: [ "staging" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install -f MyWebApp/pom.xml

    - name: Run Unit Tests
      run: mvn test -f MyWebApp/pom.xml

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=my-org
          -Dsonar.projectKey=MyWebApp
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Upload WAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mywebapp-war
        path: MyWebApp/target/MyWebApp.war

    - name: Deploy to Tomcat
      run: |
        echo "Deploying WAR to Tomcat on EC2..."
        curl -v -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
        -T MyWebApp/target/MyWebApp.war \
        "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/MyWebApp&update=true"
